name: HRRR-AWS-cookbook-dev
channels:
  - conda-forge
dependencies:
  - python<3.13  # to avoid a dependency conflict with JupyterBook 1.0.3
  - jupyter-book
  - jupyterlab
  - dask
  - metpy
  - zarr
  - s3fs
  - sphinx-pythia-theme
