name: publish-book

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ktyle/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      environment_name: HRRR-AWS-cookbook-dev
      
  deploy:
    needs: build
    uses: ktyle/cookbook-actions/.github/workflows/deploy-book.yaml@main
  
