name: trigger-book-build
on:
  pull_request:

jobs:
  build:
    uses: ktyle/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      environment_name: HRRR-AWS-cookbook-dev
      artifact_name: book-zip-${{ github.event.number }}

 
